stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/your-application.war

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - curl --upload-file /home/gitlab-runner/builds/glrt-3qU/0/rick.winkens/gitlab-ci-petclinic/target/petclinic.war --user admin:admin http://localhost:8080/manager/text/deploy?path=/petclinic
  only:
    - master