stages:
  - build
  -deploy

build:
  - mvn clean install

deploy:
  stage: deploy
  script:
    - cp target/petclinic.war //home/rickwinkens/Documents/apache-tomcat-9.0.75/webapps
  only:
    - master