build:
  stage: build
  tags: 
     - runner
  script:
     - sudo mvn clean install

deploy:
  stage: deploy
  tags:
     - runner
  script:
     - cd /home/rickwinkens/Documents/devoteam-traineeship-petclinic 
     - sudo mvn deploy

  only:
     - master
     