stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.8.4
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/petclinic.war

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - curl --upload-file target/petclinic.war http://localhost:8080/petclinic
  only:
    - master
