stages:
  - build
  - deploy_to_tomcat

build:
  stage: build
  tags:
    - runner
  script:
    - mvn clean package -Dversion=5.3.8

deploy_to_tomcat:
  stage: deploy_snapshot
  tags:
    - runner
  script:
    - mvn clean deploy -Dversion=5.3.8
    - sudo rm -rf /opt/tomcat/apache-tomcat-9.0.76/webapps/petclinic*
    - sudo cp -r target/petclinic.war /opt/tomcat/apache-tomcat-9.0.76/webapps
