stages:
  - build
  - deploy_snapshot
  - deploy_release

build:
  stage: build
  script:
    - mvn clean install

deploy_snapshot:
  stage: deploy_snapshot
  script:
    - mvn deploy -Dmaven.test.skip=true --settings settings.xml
  only:
    variables:
      - $DEPLOY_SNAPSHOT == "true"

deploy_release:
  stage: deploy_release
  script:
    - mvn deploy -Dmaven.test.skip=true --settings settings.xml
  only:
    variables:
      - $DEPLOY_RELEASE == "false"
