stages:
  - build
  - deploy
  - release

build:
  stage: build
  tags:
    - runner
  script:
    - mvn clean package

deploy_to_tomcat:
  stage: deploy
  tags:
    - runner
  script:
    - mvn clean package
    - rm -rf /home/rickwinkens/Documents/apache-tomcat-9.0.75/webapps/petclinic*
    - unzip -q target/petclinic.war -d /home/rickwinkens/Documents/apache-tomcat-9.0.75/webapps/petclinic

release:
  stage: release
  tags:
    - runner
  script:
    - echo "Deploying artifact to Nexus as a Snapshot..."
    - mvn deploy:deploy-file -Dfile=$(ls target/*.war) -DrepositoryId=nexus-snapshots -Durl=http://192.168.2.165:8081/repository/maven-snapshots/ -Dversion=5.3.8-SNAPSHOT -DgroupId=com.example -DartifactId=my-artifact -Dpackaging=war    

  only:
    - master


