trigger:
  branches:
    include:
      - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        pool:
          name: Azure Agent Rick
        steps:
          - script: |
              mvn clean compile -Dversion=5.3.8-SNAPSHOT
          - task: CopyFiles@2
            displayName: 'Copy JMeter script to build artifacts'
            inputs:
              SourceFolder: 'jmeter-tests'
              contents: '*.jmx'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - stage: deploy_to_tomcat
    displayName: Deploy to Tomcat
    dependsOn: build
    jobs:
      - job: deploy_to_tomcat
        displayName: Deploy to Tomcat
        pool:
          name: Azure Agent Rick
        steps:
          - script: |
              mvn clean deploy -Dversion=5.3.8-SNAPSHOT
              sudo rm -rf /opt/tomcat/apache-tomcat-9.0.76/webapps/petclinic*
              sudo cp /home/rickwinkens/myagent/_work/2/s/target/petclinic.war /opt/tomcat/apache-tomcat-9.0.76/webapps

  - stage: JMeterLoadTest
    displayName: 'JMeter Load Test'
    dependsOn: Build

    jobs:
    - job: RunJmeterLoadTest
      pool:
       name: Azure Agent Rick

      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Build Artifact'
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'

      - script: | 
          jmeter -n -t $(Pipeline.Workspace)/jmeter-tests/*.jmx -l $(Pipeline.Workspace)/result.jtl

      - task: PublishTestResults@2
        displayName: 'Publish JMeter test results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/results.jtl'
          failTaskOnFailedTests: True              





