trigger:
  branches:
    include:
      - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        pool:
          name: Azure Agent Rick
        steps:
          - script: |
              mvn clean compile -Dversion=5.3.8-SNAPSHOT

  - stage: deploy_to_tomcat
    displayName: Deploy to Tomcat
    dependsOn: build
    jobs:
      - job: deploy_to_tomcat
        displayName: Deploy to Tomcat
        pool:
          name: Azure Agent Rick
        steps:
          - script: |
              mvn clean deploy -Dversion=5.3.8-SNAPSHOT
              sudo rm -rf /opt/tomcat/apache-tomcat-9.0.76/webapps/petclinic*
              sudo cp /home/rickwinkens/myagent/_work/2/s/target/petclinic.war /opt/tomcat/apache-tomcat-9.0.76/webapps
              
